<?xml version="1.0"?>
<package format="3">
  <name>motion_control</name>
  <version>0.0.1</version>
  <description>Motion control node for Hunter PyBullet RL</description>
  <maintainer email="you@example.com">Phat Vo</maintainer>
  <license>MIT</license>

  <buildtool_depend>ament_cmake</buildtool_depend>
  <depend>rclcpp</depend>
  <depend>nav_msgs</depend>
  <depend>ackermann_msgs</depend>
  <exec_depend>ament_index_python</exec_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
